import { useState } from "react";
import { motion } from "framer-motion";
import { Plus, Search, List, LayoutGrid, Zap, Link2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import TaskDetailModal from "@/components/tasks/TaskDetailModal";
import CustomFieldsSection, { CustomField } from "@/components/CustomFieldsSection";
import SelectWithAddNew from "@/components/SelectWithAddNew";
import { templeTasks, type TempleTask, type TaskPriority, type TaskStatus, type SourceModule, taskPriorities, taskStatuses, sourceModules, assigneeTypes, assigneePool, templeStructures } from "@/data/taskData";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Open: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Completed: "bg-green-50 text-green-700 border-green-200", Overdue: "bg-red-50 text-red-700 border-red-200", Cancelled: "bg-muted text-muted-foreground" };

const kanbanStatuses: TaskStatus[] = ["Open", "In Progress", "Overdue", "Completed"];

const AllTasks = () => {
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [priorityFilter, setPriorityFilter] = useState("all");
  const [sourceFilter, setSourceFilter] = useState("all");
  const [structureFilter, setStructureFilter] = useState("all");
  const [viewMode, setViewMode] = useState<"table" | "kanban">("table");
  const [selectedTask, setSelectedTask] = useState<TempleTask | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [customFields, setCustomFields] = useState<CustomField[]>([]);
  const [perPage, setPerPage] = useState(25);

  const filtered = templeTasks.filter(t => {
    const ms = !search || t.title.toLowerCase().includes(search.toLowerCase()) || t.id.toLowerCase().includes(search.toLowerCase()) || t.assignedTo.toLowerCase().includes(search.toLowerCase());
    const mst = statusFilter === "all" || t.status === statusFilter;
    const mp = priorityFilter === "all" || t.priority === priorityFilter;
    const mso = sourceFilter === "all" || t.sourceModule === sourceFilter;
    const mstr = structureFilter === "all" || t.structureName === structureFilter;
    return ms && mst && mp && mso && mstr;
  });

  const structures = [...new Set(templeTasks.map(t => t.structureName))];

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">All Tasks</h1>
          <p className="text-muted-foreground text-sm">{templeTasks.length} tasks — {templeTasks.filter(t => t.autoGenerated).length} auto-generated</p>
        </div>
        <div className="flex gap-2">
          <div className="flex border rounded-lg overflow-hidden">
            <button className={`px-3 py-1.5 text-xs ${viewMode === "table" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`} onClick={() => setViewMode("table")}><List className="h-4 w-4" /></button>
            <button className={`px-3 py-1.5 text-xs ${viewMode === "kanban" ? "bg-primary text-primary-foreground" : "bg-background text-muted-foreground hover:bg-muted"}`} onClick={() => setViewMode("kanban")}><LayoutGrid className="h-4 w-4" /></button>
          </div>
          <Button size="sm" onClick={() => { setCustomFields([]); setShowCreate(true); }}><Plus className="h-4 w-4 mr-1.5" />Create Task</Button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input placeholder="Search tasks..." className="pl-9 h-9" value={search} onChange={e => setSearch(e.target.value)} />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-36 h-9 bg-background"><SelectValue placeholder="Status" /></SelectTrigger>
          <SelectContent className="bg-popover"><SelectItem value="all">All Statuses</SelectItem>{taskStatuses.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
        </Select>
        <Select value={priorityFilter} onValueChange={setPriorityFilter}>
          <SelectTrigger className="w-32 h-9 bg-background"><SelectValue placeholder="Priority" /></SelectTrigger>
          <SelectContent className="bg-popover"><SelectItem value="all">All Priorities</SelectItem>{taskPriorities.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent>
        </Select>
        <Select value={sourceFilter} onValueChange={setSourceFilter}>
          <SelectTrigger className="w-36 h-9 bg-background"><SelectValue placeholder="Source" /></SelectTrigger>
          <SelectContent className="bg-popover"><SelectItem value="all">All Sources</SelectItem>{sourceModules.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
        </Select>
        <Select value={structureFilter} onValueChange={setStructureFilter}>
          <SelectTrigger className="w-40 h-9 bg-background"><SelectValue placeholder="Structure" /></SelectTrigger>
          <SelectContent className="bg-popover"><SelectItem value="all">All Structures</SelectItem>{structures.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
        </Select>
      </div>

      {/* TABLE VIEW */}
      {viewMode === "table" && (
        <>
          <div className="border rounded-lg">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Task ID</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Source</TableHead>
                  <TableHead>Structure</TableHead>
                  <TableHead>Assigned To</TableHead>
                  <TableHead>Due Date</TableHead>
                  <TableHead>Priority</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.slice(0, perPage).map(t => {
                  const linked = t.eventName || t.sevaName || t.kitchenBatchId || t.stockTransactionId || t.freelancerName || t.maintenanceRequestId || t.darshanSlotId;
                  return (
                    <TableRow key={t.id} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                      <TableCell className="font-mono text-xs">{t.id}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1.5">
                          {t.autoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                          <div>
                            <p className="text-sm font-medium">{t.title}</p>
                            {linked && <p className="text-xs text-muted-foreground flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{linked}</p>}
                          </div>
                        </div>
                      </TableCell>
                      <TableCell><Badge variant="outline" className="text-[10px]">{t.sourceModule}</Badge></TableCell>
                      <TableCell className="text-sm">{t.structureName}</TableCell>
                      <TableCell>
                        <p className="text-sm">{t.assignedTo}</p>
                        <p className="text-[10px] text-muted-foreground">{t.assigneeType}</p>
                      </TableCell>
                      <TableCell className={`text-sm ${t.status === "Overdue" ? "text-destructive font-medium" : ""}`}>{t.dueDate}</TableCell>
                      <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                      <TableCell><Badge variant="outline" className={`text-[10px] ${statusColor[t.status]}`}>{t.status}</Badge></TableCell>
                    </TableRow>
                  );
                })}
                {filtered.length === 0 && <TableRow><TableCell colSpan={8} className="text-center py-8 text-muted-foreground">No tasks found</TableCell></TableRow>}
              </TableBody>
            </Table>
          </div>
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>Showing {Math.min(filtered.length, perPage)} of {filtered.length} tasks</span>
            <div className="flex items-center gap-2">
              <span>Per page:</span>
              {[10, 25, 50, 100].map(n => (
                <button key={n} onClick={() => setPerPage(n)} className={`px-2 py-1 rounded ${perPage === n ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`}>{n}</button>
              ))}
            </div>
          </div>
        </>
      )}

      {/* KANBAN VIEW */}
      {viewMode === "kanban" && (
        <div className="grid grid-cols-4 gap-4">
          {kanbanStatuses.map(status => {
            const tasks = filtered.filter(t => t.status === status);
            return (
              <div key={status} className="space-y-3">
                <div className="flex items-center justify-between">
                  <Badge variant="outline" className={`${statusColor[status]}`}>{status}</Badge>
                  <span className="text-xs text-muted-foreground font-medium">{tasks.length}</span>
                </div>
                <div className="space-y-2 min-h-[200px]">
                  {tasks.map(t => (
                    <Card key={t.id} className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => setSelectedTask(t)}>
                      <CardContent className="p-3 space-y-2">
                        <div className="flex items-center justify-between">
                          <span className="text-[10px] font-mono text-muted-foreground">{t.id}</span>
                          <Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge>
                        </div>
                        <div className="flex items-center gap-1">
                          {t.autoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                          <p className="text-sm font-medium leading-tight">{t.title}</p>
                        </div>
                        <div className="flex items-center justify-between text-[10px] text-muted-foreground">
                          <span>{t.assignedTo}</span>
                          <span>{t.dueDate}</span>
                        </div>
                        <div className="flex gap-1">
                          <Badge variant="outline" className="text-[10px]">{t.sourceModule}</Badge>
                          <Badge variant="outline" className="text-[10px]">{t.structureName}</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                  {tasks.length === 0 && <div className="text-xs text-muted-foreground text-center py-8 border-2 border-dashed rounded-lg">No tasks</div>}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Create Task Modal */}
      <Dialog open={showCreate} onOpenChange={setShowCreate}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader><DialogTitle>Create New Task</DialogTitle></DialogHeader>
          <div className="space-y-4">
            <div><Label>Task Title</Label><Input placeholder="Enter task title" /></div>
            <div><Label>Description</Label><Textarea placeholder="Task description..." rows={2} /></div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Structure *</Label>
                <Select>
                  <SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                  <SelectContent className="bg-popover">{templeStructures.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div>
                <Label>Priority</Label>
                <Select>
                  <SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                  <SelectContent className="bg-popover">{taskPriorities.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Assigned To</Label>
                <Select>
                  <SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                  <SelectContent className="bg-popover">{assigneePool.map(a => <SelectItem key={a.name} value={a.name}>{a.name} ({a.type})</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div>
                <Label>Linked Module</Label>
                <Select>
                  <SelectTrigger className="bg-background"><SelectValue placeholder="Optional" /></SelectTrigger>
                  <SelectContent className="bg-popover">{sourceModules.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div><Label>Start Date</Label><Input type="date" /></div>
              <div><Label>Due Date</Label><Input type="date" /></div>
            </div>
            <CustomFieldsSection fields={customFields} onFieldsChange={setCustomFields} />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreate(false)}>Cancel</Button>
            <Button onClick={() => setShowCreate(false)}>Create Task</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <TaskDetailModal task={selectedTask} open={!!selectedTask} onOpenChange={() => setSelectedTask(null)} />
    </motion.div>
  );
};

export default AllTasks;
