import { useState } from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CheckCircle2, Zap, Link2 } from "lucide-react";
import TaskDetailModal from "@/components/tasks/TaskDetailModal";
import { templeTasks, type TempleTask } from "@/data/taskData";

const CompletedTasks = () => {
  const [selectedTask, setSelectedTask] = useState<TempleTask | null>(null);
  const completed = templeTasks.filter(t => t.status === "Completed");

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2">
          <CheckCircle2 className="h-5 w-5 text-green-600" />Completed Tasks
        </h1>
        <p className="text-muted-foreground text-sm">{completed.length} tasks completed</p>
      </div>

      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Task ID</TableHead>
              <TableHead>Title</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Structure</TableHead>
              <TableHead>Assigned To</TableHead>
              <TableHead>Due Date</TableHead>
              <TableHead>Attachments</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {completed.map(t => {
              const linked = t.eventName || t.sevaName || t.kitchenBatchId || t.freelancerName;
              return (
                <TableRow key={t.id} className="cursor-pointer opacity-80 hover:opacity-100" onClick={() => setSelectedTask(t)}>
                  <TableCell className="font-mono text-xs">{t.id}</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      {t.autoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                      <div>
                        <p className="text-sm font-medium">{t.title}</p>
                        {linked && <p className="text-xs text-muted-foreground flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{linked}</p>}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className="text-[10px]">{t.sourceModule}</Badge></TableCell>
                  <TableCell className="text-sm">{t.structureName}</TableCell>
                  <TableCell>
                    <p className="text-sm">{t.assignedTo}</p>
                    <p className="text-[10px] text-muted-foreground">{t.assigneeType}</p>
                  </TableCell>
                  <TableCell className="text-sm">{t.dueDate}</TableCell>
                  <TableCell>
                    {t.attachments.length > 0 ? (
                      <Badge variant="secondary" className="text-[10px]">{t.attachments.length} files</Badge>
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </TableCell>
                </TableRow>
              );
            })}
            {completed.length === 0 && <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">No completed tasks</TableCell></TableRow>}
          </TableBody>
        </Table>
      </div>

      <TaskDetailModal task={selectedTask} open={!!selectedTask} onOpenChange={() => setSelectedTask(null)} />
    </motion.div>
  );
};

export default CompletedTasks;
