import { useState } from "react";
import { motion } from "framer-motion";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Zap, Link2 } from "lucide-react";
import TaskDetailModal from "@/components/tasks/TaskDetailModal";
import { templeTasks, myUserId, type TempleTask } from "@/data/taskData";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Open: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Completed: "bg-green-50 text-green-700 border-green-200", Overdue: "bg-red-50 text-red-700 border-red-200", Cancelled: "bg-muted text-muted-foreground" };

const MyTasks = () => {
  const [selectedTask, setSelectedTask] = useState<TempleTask | null>(null);
  const myTasks = templeTasks.filter(t => t.assignedTo === myUserId && t.status !== "Completed" && t.status !== "Cancelled");
  const completedToday = templeTasks.filter(t => t.assignedTo === myUserId && t.status === "Completed" && t.dueDate === "2026-02-10");

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">My Tasks</h1>
        <p className="text-muted-foreground text-sm">Tasks assigned to {myUserId} — {myTasks.length} active, {completedToday.length} completed today</p>
      </div>

      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Task ID</TableHead>
              <TableHead>Title</TableHead>
              <TableHead>Source</TableHead>
              <TableHead>Structure</TableHead>
              <TableHead>Due Date</TableHead>
              <TableHead>Priority</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {myTasks.map(t => {
              const linked = t.eventName || t.sevaName || t.kitchenBatchId || t.freelancerName;
              return (
                <TableRow key={t.id} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                  <TableCell className="font-mono text-xs">{t.id}</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      {t.autoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                      <div>
                        <p className="text-sm font-medium">{t.title}</p>
                        {linked && <p className="text-xs text-muted-foreground flex items-center gap-1"><Link2 className="h-3 w-3 text-primary" />{linked}</p>}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className="text-[10px]">{t.sourceModule}</Badge></TableCell>
                  <TableCell className="text-sm">{t.structureName}</TableCell>
                  <TableCell className={`text-sm ${t.status === "Overdue" ? "text-destructive font-medium" : ""}`}>{t.dueDate}</TableCell>
                  <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                  <TableCell><Badge variant="outline" className={`text-[10px] ${statusColor[t.status]}`}>{t.status}</Badge></TableCell>
                </TableRow>
              );
            })}
            {myTasks.length === 0 && <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">No active tasks assigned to you</TableCell></TableRow>}
          </TableBody>
        </Table>
      </div>

      {completedToday.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-muted-foreground mb-2">Completed Today</h2>
          <div className="border rounded-lg">
            <Table>
              <TableHeader>
                <TableRow><TableHead>Task ID</TableHead><TableHead>Title</TableHead><TableHead>Source</TableHead><TableHead>Due</TableHead></TableRow>
              </TableHeader>
              <TableBody>
                {completedToday.map(t => (
                  <TableRow key={t.id} className="cursor-pointer opacity-70" onClick={() => setSelectedTask(t)}>
                    <TableCell className="font-mono text-xs">{t.id}</TableCell>
                    <TableCell className="text-sm">{t.title}</TableCell>
                    <TableCell><Badge variant="outline" className="text-[10px]">{t.sourceModule}</Badge></TableCell>
                    <TableCell className="text-sm">{t.dueDate}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      )}

      <TaskDetailModal task={selectedTask} open={!!selectedTask} onOpenChange={() => setSelectedTask(null)} />
    </motion.div>
  );
};

export default MyTasks;
