import { useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Clock, AlertTriangle, CheckCircle2, Zap, MapPin, Calendar, ClipboardList } from "lucide-react";
import TaskDetailModal from "@/components/tasks/TaskDetailModal";
import { templeTasks, type TempleTask } from "@/data/taskData";

const priorityColor: Record<string, string> = { Critical: "bg-red-50 text-red-700 border-red-200", High: "bg-orange-50 text-orange-700 border-orange-200", Medium: "bg-amber-50 text-amber-700 border-amber-200", Low: "bg-green-50 text-green-700 border-green-200" };
const statusColor: Record<string, string> = { Open: "bg-blue-50 text-blue-700 border-blue-200", "In Progress": "bg-amber-50 text-amber-700 border-amber-200", Completed: "bg-green-50 text-green-700 border-green-200", Overdue: "bg-red-50 text-red-700 border-red-200", Cancelled: "bg-muted text-muted-foreground" };

const TaskDashboard = () => {
  const [selectedTask, setSelectedTask] = useState<TempleTask | null>(null);

  const openTasks = templeTasks.filter(t => t.status === "Open" || t.status === "In Progress");
  const dueTodayTasks = templeTasks.filter(t => t.dueDate === "2026-02-10" && t.status !== "Completed" && t.status !== "Cancelled");
  const overdueTasks = templeTasks.filter(t => t.status === "Overdue");
  const autoCount = templeTasks.filter(t => t.autoGenerated).length;

  // Structure-wise
  const structureMap = templeTasks.reduce((acc, t) => {
    if (t.status !== "Completed" && t.status !== "Cancelled") {
      if (!acc[t.structureName]) acc[t.structureName] = { total: 0, overdue: 0 };
      acc[t.structureName].total++;
      if (t.status === "Overdue") acc[t.structureName].overdue++;
    }
    return acc;
  }, {} as Record<string, { total: number; overdue: number }>);

  // Event-wise
  const eventMap = templeTasks.reduce((acc, t) => {
    if (t.eventName) {
      if (!acc[t.eventName]) acc[t.eventName] = { total: 0, completed: 0, open: 0 };
      acc[t.eventName].total++;
      if (t.status === "Completed") acc[t.eventName].completed++;
      else acc[t.eventName].open++;
    }
    return acc;
  }, {} as Record<string, { total: number; completed: number; open: number }>);

  const kpis = [
    { label: "Total Open", value: openTasks.length, icon: ClipboardList, color: "text-primary", bg: "bg-primary/5" },
    { label: "Due Today", value: dueTodayTasks.length, icon: Clock, color: "text-blue-600", bg: "bg-blue-50" },
    { label: "Overdue", value: overdueTasks.length, icon: AlertTriangle, color: "text-destructive", bg: "bg-red-50" },
    { label: "Auto-Generated", value: autoCount, icon: Zap, color: "text-purple-600", bg: "bg-purple-50" },
    { label: "Completed Today", value: templeTasks.filter(t => t.status === "Completed" && t.dueDate === "2026-02-10").length, icon: CheckCircle2, color: "text-green-600", bg: "bg-green-50" },
  ];

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Task Dashboard</h1>
        <p className="text-muted-foreground text-sm">Operational tasks linked to Events, Sevas, Kitchen, Inventory & Maintenance</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {kpis.map((kpi, i) => (
          <Card key={i} className="hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${kpi.bg} mb-2`}>
                <kpi.icon className={`h-5 w-5 ${kpi.color}`} />
              </div>
              <p className="text-2xl font-bold">{kpi.value}</p>
              <p className="text-[11px] text-muted-foreground">{kpi.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Due Today */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Clock className="h-4 w-4 text-blue-600" />Tasks Due Today
              <Badge variant="secondary" className="text-xs">{dueTodayTasks.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Task</TableHead><TableHead>Assignee</TableHead><TableHead>Priority</TableHead><TableHead>Status</TableHead></TableRow></TableHeader>
              <TableBody>
                {dueTodayTasks.slice(0, 6).map(t => (
                  <TableRow key={t.id} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                    <TableCell>
                      <div className="flex items-center gap-1.5">
                        {t.autoGenerated && <Zap className="h-3 w-3 text-purple-500 shrink-0" />}
                        <div>
                          <p className="text-sm font-medium">{t.title}</p>
                          <p className="text-xs text-muted-foreground">{t.id} · {t.sourceModule}</p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell className="text-sm">{t.assignedTo}</TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${statusColor[t.status]}`}>{t.status}</Badge></TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Overdue */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <AlertTriangle className="h-4 w-4 text-destructive" />Overdue Tasks
              <Badge variant="destructive" className="text-xs">{overdueTasks.length}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Task</TableHead><TableHead>Due</TableHead><TableHead>Assignee</TableHead><TableHead>Priority</TableHead></TableRow></TableHeader>
              <TableBody>
                {overdueTasks.map(t => (
                  <TableRow key={t.id} className="cursor-pointer" onClick={() => setSelectedTask(t)}>
                    <TableCell>
                      <p className="text-sm font-medium">{t.title}</p>
                      <p className="text-xs text-muted-foreground">{t.sourceModule}</p>
                    </TableCell>
                    <TableCell className="text-sm text-destructive font-medium">{t.dueDate}</TableCell>
                    <TableCell className="text-sm">{t.assignedTo}</TableCell>
                    <TableCell><Badge variant="outline" className={`text-[10px] ${priorityColor[t.priority]}`}>{t.priority}</Badge></TableCell>
                  </TableRow>
                ))}
                {overdueTasks.length === 0 && <TableRow><TableCell colSpan={4} className="text-center py-6 text-muted-foreground">No overdue tasks</TableCell></TableRow>}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Tasks by Structure */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" />Tasks by Structure</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Structure</TableHead><TableHead className="text-center">Active</TableHead><TableHead className="text-center">Overdue</TableHead></TableRow></TableHeader>
              <TableBody>
                {Object.entries(structureMap).sort((a, b) => b[1].total - a[1].total).map(([name, data]) => (
                  <TableRow key={name}>
                    <TableCell className="font-medium text-sm">{name}</TableCell>
                    <TableCell className="text-center text-sm">{data.total}</TableCell>
                    <TableCell className="text-center">{data.overdue > 0 ? <Badge variant="destructive" className="text-xs">{data.overdue}</Badge> : <span className="text-xs text-muted-foreground">0</span>}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        {/* Tasks by Event */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2"><Calendar className="h-4 w-4 text-primary" />Tasks by Event</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader><TableRow><TableHead>Event</TableHead><TableHead className="text-center">Total</TableHead><TableHead className="text-center">Done</TableHead><TableHead className="text-center">Pending</TableHead></TableRow></TableHeader>
              <TableBody>
                {Object.entries(eventMap).map(([name, data]) => (
                  <TableRow key={name}>
                    <TableCell className="font-medium text-sm">{name}</TableCell>
                    <TableCell className="text-center text-sm">{data.total}</TableCell>
                    <TableCell className="text-center text-sm text-green-600">{data.completed}</TableCell>
                    <TableCell className="text-center text-sm text-amber-600">{data.open}</TableCell>
                  </TableRow>
                ))}
                {Object.keys(eventMap).length === 0 && <TableRow><TableCell colSpan={4} className="text-center py-6 text-muted-foreground">No event-linked tasks</TableCell></TableRow>}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      <TaskDetailModal task={selectedTask} open={!!selectedTask} onOpenChange={() => setSelectedTask(null)} />
    </motion.div>
  );
};

export default TaskDashboard;
