import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Plus, Search, Filter, Link2, Package, Zap } from "lucide-react";
import TaskDetailModal, { type TaskDetail } from "@/components/tasks/TaskDetailModal";
import { autoTasks } from "@/data/templeData";

const priorityColor: Record<string, string> = {
  Critical: "bg-red-100 text-red-700",
  High: "bg-orange-100 text-orange-700",
  Medium: "bg-yellow-100 text-yellow-700",
  Low: "bg-green-100 text-green-700",
};

const statusColor: Record<string, string> = {
  Open: "bg-blue-100 text-blue-700",
  "In Progress": "bg-amber-100 text-amber-700",
  Completed: "bg-green-100 text-green-700",
  Blocked: "bg-red-100 text-red-700",
  Assigned: "bg-indigo-100 text-indigo-700",
};

const sourceTypeColor: Record<string, string> = {
  "Event-Freelancer": "bg-purple-100 text-purple-700",
  "Event-Volunteer": "bg-cyan-100 text-cyan-700",
  "Event-Material": "bg-amber-100 text-amber-700",
  "Kitchen-Batch": "bg-orange-100 text-orange-700",
  "Seva-Daily": "bg-emerald-100 text-emerald-700",
  "Manual": "bg-muted text-muted-foreground",
};

const TaskList = () => {
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [sourceFilter, setSourceFilter] = useState("all");
  const [createOpen, setCreateOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<typeof autoTasks[0] | null>(null);

  const allTasks = autoTasks;

  const filtered = allTasks.filter((t) => {
    const matchSearch = t.title.toLowerCase().includes(search.toLowerCase()) || t.id.toLowerCase().includes(search.toLowerCase());
    const matchCategory = categoryFilter === "all" || t.category === categoryFilter;
    const matchStatus = statusFilter === "all" || t.status === statusFilter;
    const matchSource = sourceFilter === "all" || (sourceFilter === "auto" ? t.autoGenerated : !t.autoGenerated);
    return matchSearch && matchCategory && matchStatus && matchSource;
  });

  const autoCount = allTasks.filter(t => t.autoGenerated).length;
  const manualCount = allTasks.filter(t => !t.autoGenerated).length;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Task List</h1>
          <p className="text-muted-foreground text-sm mt-1">All tasks — manual + auto-generated from Events, Kitchen, Freelancers, and Sevas</p>
        </div>
        <Dialog open={createOpen} onOpenChange={setCreateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2"><Plus className="h-4 w-4" /> Create Task</Button>
          </DialogTrigger>
          <DialogContent className="max-w-lg bg-background">
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
              <DialogDescription>Fill in task details and assign to a person or team</DialogDescription>
            </DialogHeader>
            <div className="space-y-4 pt-2">
              <div className="space-y-1.5">
                <Label>Task Title</Label>
                <Input placeholder="Enter task title" />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label>Category</Label>
                  <Select><SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                    <SelectContent className="bg-popover">
                      {["Ritual", "Kitchen", "Event", "Maintenance", "Admin", "Security", "Procurement"].map((c) => (
                        <SelectItem key={c} value={c}>{c}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label>Priority</Label>
                  <Select><SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                    <SelectContent className="bg-popover">
                      {["Low", "Medium", "High", "Critical"].map((p) => (
                        <SelectItem key={p} value={p}>{p}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label>Linked Module</Label>
                  <Select><SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                    <SelectContent className="bg-popover">
                      {["Event Management", "Rituals & Sevas", "Kitchen & Prasadam", "Inventory", "Freelancer", "Volunteer", "None"].map((m) => (
                        <SelectItem key={m} value={m}>{m}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label>Due Date</Label>
                  <Input type="date" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label>Assign To</Label>
                  <Select><SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                    <SelectContent className="bg-popover">
                      <SelectItem value="pandit-sharma">Pandit Sharma (Employee)</SelectItem>
                      <SelectItem value="head-cook">Head Cook (Role)</SelectItem>
                      <SelectItem value="security-a">Security Team A (Team)</SelectItem>
                      <SelectItem value="pixel-studio">Pixel Studio (Freelancer)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label>Assignee Type</Label>
                  <Select><SelectTrigger className="bg-background"><SelectValue placeholder="Select" /></SelectTrigger>
                    <SelectContent className="bg-popover">
                      {["Employee", "Volunteer", "Freelancer", "Role", "Team"].map((t) => (
                        <SelectItem key={t} value={t}>{t}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-1.5">
                <Label>Notes</Label>
                <Textarea placeholder="Additional instructions..." rows={2} />
              </div>
              <div className="flex justify-end gap-2 pt-2">
                <Button variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button>
                <Button onClick={() => setCreateOpen(false)}>Create Task</Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Source Summary */}
      <div className="flex gap-4 text-sm">
        <span>Total: <strong>{allTasks.length}</strong></span>
        <span className="flex items-center gap-1"><Zap className="h-3.5 w-3.5 text-purple-500" /> Auto-Generated: <strong>{autoCount}</strong></span>
        <span>Manual: <strong>{manualCount}</strong></span>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-wrap items-center gap-3">
            <div className="relative flex-1 min-w-[200px]">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input placeholder="Search tasks..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" />
            </div>
            <Select value={categoryFilter} onValueChange={setCategoryFilter}>
              <SelectTrigger className="w-[150px] bg-background"><Filter className="h-3.5 w-3.5 mr-1.5" /><SelectValue /></SelectTrigger>
              <SelectContent className="bg-popover">
                <SelectItem value="all">All Categories</SelectItem>
                {["Ritual", "Kitchen", "Event", "Maintenance", "Admin", "Security", "Procurement"].map((c) => (
                  <SelectItem key={c} value={c}>{c}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[150px] bg-background"><SelectValue /></SelectTrigger>
              <SelectContent className="bg-popover">
                <SelectItem value="all">All Statuses</SelectItem>
                {["Open", "Assigned", "In Progress", "Completed", "Blocked"].map((s) => (
                  <SelectItem key={s} value={s}>{s}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={sourceFilter} onValueChange={setSourceFilter}>
              <SelectTrigger className="w-[150px] bg-background"><SelectValue /></SelectTrigger>
              <SelectContent className="bg-popover">
                <SelectItem value="all">All Sources</SelectItem>
                <SelectItem value="auto">Auto-Generated</SelectItem>
                <SelectItem value="manual">Manual</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[90px]">ID</TableHead>
                <TableHead>Title</TableHead>
                <TableHead>Category</TableHead>
                <TableHead>Source</TableHead>
                <TableHead>Linked To</TableHead>
                <TableHead>Priority</TableHead>
                <TableHead>Due Date</TableHead>
                <TableHead>Assignee</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filtered.map((task) => (
                <TableRow key={task.id} className="cursor-pointer hover:bg-muted/50" onClick={() => setSelectedTask(task)}>
                  <TableCell className="font-mono text-xs text-muted-foreground">{task.id}</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      {task.autoGenerated && <Zap className="h-3.5 w-3.5 text-purple-500 shrink-0" />}
                      <div>
                        <p className="font-medium text-sm">{task.title}</p>
                        {task.notes && <p className="text-xs text-muted-foreground truncate max-w-[300px]">{task.notes}</p>}
                      </div>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className="text-xs">{task.category}</Badge></TableCell>
                  <TableCell>
                    <Badge variant="outline" className={`text-[10px] ${sourceTypeColor[task.sourceType]}`}>
                      {task.sourceType.replace("-", " → ")}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    {task.linkedEntityId ? (
                      <span className="text-xs flex items-center gap-1">
                        <Link2 className="h-3 w-3 text-primary" />
                        <span className="font-mono text-primary">{task.linkedEntityId}</span>
                      </span>
                    ) : <span className="text-xs text-muted-foreground">—</span>}
                  </TableCell>
                  <TableCell><Badge variant="outline" className={`text-xs ${priorityColor[task.priority]}`}>{task.priority}</Badge></TableCell>
                  <TableCell className="text-xs">{task.dueDate}</TableCell>
                  <TableCell>
                    <div>
                      <p className="text-sm">{task.assignee}</p>
                      <p className="text-[10px] text-muted-foreground">{task.assigneeType}</p>
                    </div>
                  </TableCell>
                  <TableCell><Badge variant="outline" className={`text-xs ${statusColor[task.status] || ""}`}>{task.status}</Badge></TableCell>
                </TableRow>
              ))}
              {filtered.length === 0 && (
                <TableRow><TableCell colSpan={9} className="text-center py-8 text-muted-foreground">No tasks found</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <TaskDetailModal
        task={selectedTask ? { ...selectedTask, linkedModule: selectedTask.linkedModule } as TaskDetail : null}
        open={!!selectedTask}
        onOpenChange={() => setSelectedTask(null)}
      />
    </div>
  );
};

export default TaskList;
