import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ClipboardList, AlertTriangle, CalendarDays, Clock, ArrowRight, CheckCircle2, Flag, Zap, Package, Users } from "lucide-react";
import TaskDetailModal, { type TaskDetail } from "@/components/tasks/TaskDetailModal";
import { autoTasks } from "@/data/templeData";

const priorityColor: Record<string, string> = {
  Critical: "bg-red-100 text-red-700",
  High: "bg-orange-100 text-orange-700",
  Medium: "bg-yellow-100 text-yellow-700",
  Low: "bg-green-100 text-green-700",
};

const statusColor: Record<string, string> = {
  Open: "bg-blue-100 text-blue-700",
  "In Progress": "bg-amber-100 text-amber-700",
  Completed: "bg-green-100 text-green-700",
  Blocked: "bg-red-100 text-red-700",
  Assigned: "bg-indigo-100 text-indigo-700",
};

const sourceIcon: Record<string, React.ReactNode> = {
  "Event-Freelancer": <Users className="h-3 w-3 text-purple-500" />,
  "Event-Volunteer": <Users className="h-3 w-3 text-cyan-500" />,
  "Event-Material": <Package className="h-3 w-3 text-amber-500" />,
  "Kitchen-Batch": <ClipboardList className="h-3 w-3 text-orange-500" />,
  "Seva-Daily": <CalendarDays className="h-3 w-3 text-emerald-500" />,
  "Manual": null,
};

const TaskDashboard = () => {
  const [selectedTask, setSelectedTask] = useState<TaskDetail | null>(null);

  const allTasks = autoTasks;
  const dueTodayTasks = allTasks.filter(t => t.dueDate === "2026-02-10" || t.dueDate === "2026-02-09");
  const overdueTasks = allTasks.filter(t => t.dueDate < "2026-02-09" && t.status !== "Completed");
  const autoGenCount = allTasks.filter(t => t.autoGenerated).length;
  const eventLinked = allTasks.filter(t => t.sourceType.startsWith("Event")).length;
  const highPriority = allTasks.filter(t => t.priority === "High" || t.priority === "Critical").length;

  const stats = [
    { label: "Due Today", value: dueTodayTasks.length, icon: Clock, color: "text-blue-600 bg-blue-50" },
    { label: "Overdue", value: overdueTasks.length, icon: AlertTriangle, color: "text-red-600 bg-red-50" },
    { label: "High Priority", value: highPriority, icon: Flag, color: "text-orange-600 bg-orange-50" },
    { label: "Auto-Generated", value: autoGenCount, icon: Zap, color: "text-purple-600 bg-purple-50" },
    { label: "Event-Linked", value: eventLinked, icon: CalendarDays, color: "text-indigo-600 bg-indigo-50" },
  ];

  const sourceBreakdown = [
    { source: "Event → Freelancer", count: allTasks.filter(t => t.sourceType === "Event-Freelancer").length, color: "bg-purple-500" },
    { source: "Event → Volunteer", count: allTasks.filter(t => t.sourceType === "Event-Volunteer").length, color: "bg-cyan-500" },
    { source: "Event → Material", count: allTasks.filter(t => t.sourceType === "Event-Material").length, color: "bg-amber-500" },
    { source: "Kitchen → Batch", count: allTasks.filter(t => t.sourceType === "Kitchen-Batch").length, color: "bg-orange-500" },
    { source: "Seva → Daily", count: allTasks.filter(t => t.sourceType === "Seva-Daily").length, color: "bg-emerald-500" },
    { source: "Manual", count: allTasks.filter(t => t.sourceType === "Manual").length, color: "bg-muted-foreground" },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Task Dashboard</h1>
        <p className="text-muted-foreground text-sm mt-1">Operational tasks — auto-generated from Events, Kitchen, Freelancers, and Sevas</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
        {stats.map((s) => (
          <Card key={s.label} className="border">
            <CardContent className="p-4 flex items-center gap-3">
              <div className={`p-2.5 rounded-lg ${s.color}`}>
                <s.icon className="h-5 w-5" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{s.value}</p>
                <p className="text-xs text-muted-foreground">{s.label}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base flex items-center gap-2">
                <Clock className="h-4 w-4 text-blue-600" /> Tasks Due Today
              </CardTitle>
              <Badge variant="secondary" className="text-xs">{dueTodayTasks.length}</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-2">
            {dueTodayTasks.slice(0, 6).map((task) => (
              <div
                key={task.id}
                className="flex items-center justify-between p-2.5 rounded-lg border bg-card hover:bg-muted/50 transition-colors cursor-pointer"
                onClick={() => setSelectedTask(task as unknown as TaskDetail)}
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono text-muted-foreground">{task.id}</span>
                    {task.autoGenerated && <Zap className="h-3 w-3 text-purple-500" />}
                    {sourceIcon[task.sourceType]}
                    <Badge variant="outline" className={`text-[10px] px-1.5 py-0 ${priorityColor[task.priority]}`}>{task.priority}</Badge>
                  </div>
                  <p className="text-sm font-medium text-foreground truncate">{task.title}</p>
                  <p className="text-xs text-muted-foreground">{task.assignee} · {task.assigneeType}</p>
                </div>
                <Badge variant="outline" className={`text-[10px] ${statusColor[task.status] || ""}`}>{task.status}</Badge>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-red-600" /> Overdue Tasks
              </CardTitle>
              <Badge variant="destructive" className="text-xs">{overdueTasks.length}</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-2">
            {overdueTasks.map((task) => (
              <div
                key={task.id}
                className="flex items-center justify-between p-2.5 rounded-lg border border-red-100 bg-red-50/30 hover:bg-red-50/60 transition-colors cursor-pointer"
                onClick={() => setSelectedTask(task as unknown as TaskDetail)}
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono text-muted-foreground">{task.id}</span>
                    <Badge variant="outline" className={`text-[10px] px-1.5 py-0 ${priorityColor[task.priority]}`}>{task.priority}</Badge>
                  </div>
                  <p className="text-sm font-medium text-foreground truncate">{task.title}</p>
                  <p className="text-xs text-muted-foreground">{task.assignee}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs font-medium text-red-600">Overdue</p>
                  <p className="text-[10px] text-muted-foreground">Due {task.dueDate}</p>
                </div>
              </div>
            ))}

            <div className="pt-2">
              <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <Zap className="h-4 w-4 text-purple-500" /> Tasks by Source
              </h4>
              <div className="space-y-2.5">
                {sourceBreakdown.filter(s => s.count > 0).map((src) => (
                  <div key={src.source} className="flex items-center gap-3">
                    <span className="text-xs text-muted-foreground w-32">{src.source}</span>
                    <div className="flex-1 h-2 bg-muted rounded-full overflow-hidden">
                      <div className={`h-full rounded-full ${src.color}`} style={{ width: `${(src.count / allTasks.length) * 100}%` }} />
                    </div>
                    <span className="text-xs font-medium text-foreground w-8 text-right">{src.count}</span>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <TaskDetailModal
        task={selectedTask}
        open={!!selectedTask}
        onOpenChange={() => setSelectedTask(null)}
      />
    </div>
  );
};

export default TaskDashboard;
