import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { User, Calendar, Link2, MapPin, Image, Video, FileText, Zap, Clock } from "lucide-react";
import type { TempleTask } from "@/data/taskData";

const priorityColor: Record<string, string> = {
  Critical: "bg-red-50 text-red-700 border-red-200",
  High: "bg-orange-50 text-orange-700 border-orange-200",
  Medium: "bg-amber-50 text-amber-700 border-amber-200",
  Low: "bg-green-50 text-green-700 border-green-200",
};

const statusColor: Record<string, string> = {
  Open: "bg-blue-50 text-blue-700 border-blue-200",
  "In Progress": "bg-amber-50 text-amber-700 border-amber-200",
  Completed: "bg-green-50 text-green-700 border-green-200",
  Overdue: "bg-red-50 text-red-700 border-red-200",
  Cancelled: "bg-muted text-muted-foreground",
};

interface TaskDetailModalProps {
  task: TempleTask | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const TaskDetailModal = ({ task, open, onOpenChange }: TaskDetailModalProps) => {
  if (!task) return null;

  const linkedRef = task.eventName || task.sevaName || task.darshanSlotId || task.kitchenBatchId || task.stockTransactionId || task.maintenanceRequestId || task.freelancerName;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs font-mono text-muted-foreground">{task.id}</span>
            <Badge variant="outline" className={`text-[10px] ${statusColor[task.status]}`}>{task.status}</Badge>
            <Badge variant="outline" className={`text-[10px] ${priorityColor[task.priority]}`}>{task.priority}</Badge>
            {task.autoGenerated && <Badge variant="outline" className="text-[10px] bg-purple-50 text-purple-700 border-purple-200 gap-0.5"><Zap className="h-2.5 w-2.5" />Auto</Badge>}
          </div>
          <DialogTitle className="text-lg mt-1">{task.title}</DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="overview" className="mt-2">
          <TabsList className="grid grid-cols-3 w-full">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="activity">
              Activity Log <Badge variant="secondary" className="ml-1 text-[10px] h-4 px-1">{task.activities.length}</Badge>
            </TabsTrigger>
            <TabsTrigger value="attachments">
              Attachments {task.attachments.length > 0 && <Badge variant="secondary" className="ml-1 text-[10px] h-4 px-1">{task.attachments.length}</Badge>}
            </TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="mt-4 space-y-4">
            {task.description && (
              <div className="p-3 bg-muted/50 rounded-lg border text-sm">{task.description}</div>
            )}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-3">
                <div>
                  <p className="text-[10px] uppercase text-muted-foreground font-medium">Assigned To</p>
                  <div className="flex items-center gap-1.5 text-sm mt-0.5">
                    <User className="h-3.5 w-3.5 text-muted-foreground" />
                    <span className="font-medium">{task.assignedTo}</span>
                    <Badge variant="outline" className="text-[10px]">{task.assigneeType}</Badge>
                  </div>
                </div>
                <div>
                  <p className="text-[10px] uppercase text-muted-foreground font-medium">Structure</p>
                  <div className="flex items-center gap-1.5 text-sm mt-0.5">
                    <MapPin className="h-3.5 w-3.5 text-muted-foreground" />
                    <span>{task.structureName}</span>
                  </div>
                </div>
                <div>
                  <p className="text-[10px] uppercase text-muted-foreground font-medium">Priority</p>
                  <Badge variant="outline" className={`text-xs ${priorityColor[task.priority]}`}>{task.priority}</Badge>
                </div>
              </div>
              <div className="space-y-3">
                <div>
                  <p className="text-[10px] uppercase text-muted-foreground font-medium">Dates</p>
                  <div className="flex items-center gap-1.5 text-sm mt-0.5">
                    <Calendar className="h-3.5 w-3.5 text-muted-foreground" />
                    <span>{task.startDate} → {task.dueDate}</span>
                  </div>
                </div>
                <div>
                  <p className="text-[10px] uppercase text-muted-foreground font-medium">Source Module</p>
                  <Badge variant="outline" className="text-xs">{task.sourceModule}</Badge>
                </div>
                {linkedRef && (
                  <div>
                    <p className="text-[10px] uppercase text-muted-foreground font-medium">Linked Reference</p>
                    <div className="flex items-center gap-1.5 text-sm mt-0.5">
                      <Link2 className="h-3.5 w-3.5 text-primary" />
                      <span className="text-primary font-medium">{linkedRef}</span>
                    </div>
                  </div>
                )}
              </div>
            </div>
            <Separator />
            <div className="grid grid-cols-3 gap-3 text-sm">
              <div><span className="text-muted-foreground text-xs">Temple ID:</span><p className="font-medium">{task.templeId}</p></div>
              <div><span className="text-muted-foreground text-xs">Created By:</span><p className="font-medium">{task.createdBy}</p></div>
              <div><span className="text-muted-foreground text-xs">Status:</span><Badge variant="outline" className={`text-xs ${statusColor[task.status]}`}>{task.status}</Badge></div>
            </div>
            {task.cancelReason && (
              <div className="p-3 bg-red-50 rounded-lg border border-red-200 text-sm">
                <p className="font-medium text-red-700 text-xs mb-1">Cancellation Reason</p>
                <p>{task.cancelReason}</p>
              </div>
            )}
          </TabsContent>

          <TabsContent value="activity" className="mt-4">
            <div className="space-y-0">
              {task.activities.map((act, i) => (
                <div key={i} className="flex gap-3 py-3 border-b last:border-0">
                  <div className="w-2 h-2 rounded-full bg-primary mt-2 shrink-0" />
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium">{act.action}</p>
                      <span className="text-[10px] text-muted-foreground">{act.by}</span>
                    </div>
                    <p className="text-xs text-muted-foreground flex items-center gap-1 mt-0.5">
                      <Clock className="h-3 w-3" />{act.timestamp}
                    </p>
                    {act.notes && <p className="text-xs text-muted-foreground mt-1 italic">{act.notes}</p>}
                  </div>
                </div>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="attachments" className="mt-4">
            {task.attachments.length > 0 ? (
              <div className="grid grid-cols-2 gap-3">
                {task.attachments.map((att, i) => (
                  <div key={i} className="p-4 rounded-lg border bg-card text-center hover:shadow-sm transition-shadow">
                    <div className="h-16 flex items-center justify-center mb-2 bg-muted rounded-lg">
                      {att.type === "photo" ? <Image className="h-8 w-8 text-blue-400" /> :
                       att.type === "video" ? <Video className="h-8 w-8 text-purple-400" /> :
                       <FileText className="h-8 w-8 text-gray-400" />}
                    </div>
                    <p className="text-xs font-medium truncate">{att.name}</p>
                    <p className="text-[10px] text-muted-foreground mt-0.5">{att.timestamp}</p>
                    <p className="text-[10px] text-muted-foreground">by {att.uploadedBy}</p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-10 text-sm text-muted-foreground">No attachments</div>
            )}
          </TabsContent>
        </Tabs>

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
          {task.status !== "Completed" && task.status !== "Cancelled" && <Button>Update Status</Button>}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default TaskDetailModal;
